"""Application language profiles and validated Rime mappings.

Supported application languages are EXACTLY English, Telugu, Tamil, Hindi.

Rime production catalog (fetched 2026-09-06 from
https://users.rime.ai/data/voices/all-v2.json and docs.rime.ai/docs/voices):

- coda: English (eng), Hindi (hin), plus es/fr/de/ja/pt/ar/it — NOT Tamil or Telugu
- mistv3: English, Spanish, French, German — NOT Hindi, Tamil, Telugu
- Arcana is retired (LiveKit: retired 2026-08-19). Do not use.

English and Hindi therefore use Rime Coda over WebSocket.
Tamil and Telugu use an explicit fallback provider. Output metadata never
claims those utterances were generated by Rime.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

AppLanguage = Literal["en", "te", "ta", "hi"]


@dataclass(frozen=True)
class LanguageProfile:
    language_code: AppLanguage
    language_name: str
    iso_639_2: str
    rime_enabled: bool
    rime_model: str | None
    rime_speaker: str | None
    rime_language: str | None
    audio_format: str
    transport: str
    fallback_provider: str | None
    fallback_reason: str | None
    stt_language: str
    enabled: bool = True


# Speakers taken from the live Coda catalog (not invented).
LANGUAGE_PROFILES: dict[AppLanguage, LanguageProfile] = {
    "en": LanguageProfile(
        language_code="en",
        language_name="English",
        iso_639_2="eng",
        rime_enabled=True,
        rime_model="coda",
        rime_speaker="astra",
        rime_language="en",
        audio_format="pcm",
        transport="websocket",
        fallback_provider=None,
        fallback_reason=None,
        stt_language="en",
    ),
    "hi": LanguageProfile(
        language_code="hi",
        language_name="Hindi",
        iso_639_2="hin",
        rime_enabled=True,
        rime_model="coda",
        rime_speaker="nadi",
        rime_language="hi",
        audio_format="pcm",
        transport="websocket",
        fallback_provider=None,
        fallback_reason=None,
        stt_language="hi",
    ),
    "ta": LanguageProfile(
        language_code="ta",
        language_name="Tamil",
        iso_639_2="tam",
        rime_enabled=False,
        rime_model=None,
        rime_speaker=None,
        rime_language=None,
        audio_format="pcm",
        transport="http",
        fallback_provider="edge",
        fallback_reason="unsupported_rime_language",
        stt_language="ta",
    ),
    "te": LanguageProfile(
        language_code="te",
        language_name="Telugu",
        iso_639_2="tel",
        rime_enabled=False,
        rime_model=None,
        rime_speaker=None,
        rime_language=None,
        audio_format="pcm",
        transport="http",
        fallback_provider="edge",
        fallback_reason="unsupported_rime_language",
        stt_language="te",
    ),
}


def supported_language_codes() -> list[str]:
    return list(LANGUAGE_PROFILES.keys())


def get_profile(code: str) -> LanguageProfile:
    key = code.lower().split("-")[0]
    if key not in LANGUAGE_PROFILES:
        return LANGUAGE_PROFILES["en"]
    return LANGUAGE_PROFILES[key]  # type: ignore[index]
